export const product = [
    {
        id: "item1",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134201-23030-c5gkxxzqkeov40_tn",
        secondImg: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
        name: "Áo kaki bông tuyết nam The Rustico kaki cao cấp co giãn bốn chiều mềm mịn thoải mái SM2314",
        oldPrice: "₫70.000",
        price: "₫520.000",
        sell: "Đã bán 2.1k",
        sales: "Giảm đ2k",
        flash: "",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
        size: "TRẮNG,M 40-50KG",
        display: "block"
    },
    {
        id: "item2",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lik6lwx2fy8c89_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "Quần Jeans Ống Loe Xanh Bạc, Quần Bò Nữ Ống Loe Xanh Bạc Chất Co Giãn Nhẹ Cực Xinh L03",
        oldPrice: "₫7.000",
        price: "₫1.000",
        sell: "Đã bán 2.3k",
        sales: "Giảm đ2k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item3",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lgi0wqjpu6i21a_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "Sạc dự phòng 20000mah  WP161,  pin tích điện thiết kế nhỏ gọn đèn lead hiển thị phần trăm pin kèm cáp sạc  BH 24 Tháng",
        oldPrice: "₫30.000",
        price: "₫150.000",
        sell: "Đã bán 402",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item4",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-llq9nl5sig9r3f_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "Túi xách nữ da PU thời trang hàng hiệu phong cách Hàn Quốc TX18",
        oldPrice: "₫30.000",
        price: "₫1.000",
        sell: "Đã bán 26",
        sales: "Giảm đ15k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item5",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-23030-56s1se7z0pov6c_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-e17dc23aa1eb435e675f3dfcdb10d49b",
        name: "BD15 Đầm Công Chúa Phong Cách Trung Hoa Đón Noel Và Năm Mới 2024 Cho Bé Gái Cực Kỳ Đáng Yêu - Black Dress",
        oldPrice: "₫720.000",
        price: "₫520.000",
        sell: "Đã bán 9",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item6",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-llmfwn69pdfz98_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "COWGIRL  quần ống rộng quần nữ jean phong cách Retro Ống Rộng siêu đẹp 2023 MỚI Phong cách Trendy High quality Comfortable A27L09V 36Z230909",
        oldPrice: "₫270.000",
        price: "₫195.000",
        sell: "Đã bán 2",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
 
                display: "block"
    },
    {
        id: "item7",
        firstImg: "https://down-vn.img.susercontent.com/file/b3adfbdb40e57eb9654154ac2baa1017_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "Guốc nữ quai trong 7P gót ly thời trang hàng loại 1 cao cấp Full Box Dép guốc cao gót chất mềm đi êm MT Shoes",
        oldPrice: "₫570.000",
        price: "₫369.000",
        sell: "Đã bán 5.1k",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item8",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lodtnpq79bxz2f_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "Bộ đôi chống nắng bảo vệ hoàn hảo Anessa Perfect UV Sunscreen Skincare Milk",
        oldPrice: "₫123.000",
        price: "₫610.000",
        sell: "Đã bán 98.7k",
        sales: "Giảm 50%",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item9",
        firstImg: "https://down-vn.img.susercontent.com/file/e189cdb2bd5bf81c94c0e18786981f3b_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "FC20 Váy Trắng Babydoll Phối Ren Cực Kỳ Điệu Đà Dễ Thương Phong Cách Hàn Quốc Phù Hợp Mặc Đi Nhiều Nơi",
        oldPrice: "₫15.000",
        price: "₫1000",
        sell: "Đã bán 10",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item10",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134201-7r98o-lofvskz8wqt309_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-e17dc23aa1eb435e675f3dfcdb10d49b",
        name: "Ấm Thái siêu tốc JIPLAI cao cấp 2.5L, ấm đun siêu tốc 2 lớp loại lớn - Aureliana_Store",
        oldPrice: "₫3.000",
        price: "₫1.888",
        sell: "Đã bán 503",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item11",
        firstImg: "https://down-vn.img.susercontent.com/file/sg-11134201-22120-f3h29jur9nlv37_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "áo gile trần bông có mũ hình gấu cho bé trai bé gái",
        oldPrice: "₫70.000",
        price: "₫55.000",
        sell: "Đã bán 3",
        sales: "Giảm đ20k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item12",
        firstImg: "https://down-vn.img.susercontent.com/file/sg-11134201-7qvef-lft248kqzls61e_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "Bộ lấy ráy tai INOX CAO CẤP cho bé và người lớn, dụng cụ vệ sinh tai cao cấp cho gia đình",
        oldPrice: "₫23.000",
        price: "₫7.900",
        sell: "Đã bán 1.6k",
        sales: "",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item13",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lixcnuy0rjki87_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "Set 19 món Kẹp Tóc Màu Hồng🌏FREE SHIP🌎Kẹp Tóc Nhỏ Dễ Thương Nữ 2023",
        oldPrice: "₫27.900",
        price: "₫19.999",
        sell: "Đã bán 15.5k",
        sales: "",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item14",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134201-7r98o-llub41fbg1jz31_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "Dép lông con sóc siêu cute xả khokho85k-85k sập giá",
        oldPrice: "₫111.250",
        price: "₫85.000",
        sell: "Đã bán 13k",
        sales: "Giảm đ13k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item15",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-llk5swriofk84a_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "1 cuộn túi đựng rác đen tự phân hủy loại to 55x65cm P0453",
        oldPrice: "₫10.000",
        price: "₫6.000",
        sell: "Đã bán 35.4k",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item16",
        firstImg: "https://down-vn.img.susercontent.com/file/1ce2c11a14e433e747ba27c1973a05c0_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-e17dc23aa1eb435e675f3dfcdb10d49b",
        name: "Áo Hoodie YANDO Wash P054 Thun Cotton French Terry Astronauts Guitar 350GSM Local Brand",
        oldPrice: "₫570.000",
        price: "₫432.000",
        sell: "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
        sales: "Giảm 20%",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item17",
        firstImg: "https://down-vn.img.susercontent.com/file/459f9e062f0557b2e13d2c1a52f790b1_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "Thắt lưng nam Dabaraac da cao cấp khóa kim loại tự động không gỉ - Cam kết 1 đổi 1 bảo hành 12 tháng TL58",
        oldPrice: "₫20.000",
        price: "₫9.000",
        sell: "Đã bán 13.1k",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item18",
        firstImg: "https://down-vn.img.susercontent.com/file/sg-11134201-22110-3ka1gd80sijvac_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "Túi tote đeo chéo vải canvas trơn nam nữ cỡ nhỏ đi chơi dễ phối đồ phong cách Hàn Quốc DC11",
        oldPrice: "₫85.200",
        price: "₫69.000",
        sell: "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
        sales: "Giảm đ5k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item19",
        firstImg: "https://down-vn.img.susercontent.com/file/cca2c37f093eefeee19687c007a33462_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "BÔNG TẨY TRANG 222 MIẾNG KHÔNG TƯA BÔNG",
        oldPrice: "₫70.000",
        price: "₫4.500",
        sell: "Đã bán 4.1k",
        sales: "",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item20",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lf7xjoau0od36c_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "Ly Giữ Nhiệt Iced Americano Chất Liệu Inox 304 Cao Cấp Dung Tích 600ml Nắp Chống Tràn An Toàn Vệ Sinh",
        oldPrice: "₫65.000",
        price: "₫5.000",
        sell: "Đã bán 9.7k",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item21",
        firstImg: "https://down-vn.img.susercontent.com/file/sg-11134201-22100-64j8khrk2fivb7_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "[Mã SGMST20K giảm 20K đơn 0đ] Sách - Nhật Ký Trong Tù (Tái Bản)",
        oldPrice: "₫320.000",
        price: "₫289.000",
        sell: "Đã bán 266.8k",
        sales: "",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item22",
        firstImg: "https://down-vn.img.susercontent.com/file/cea0adbaff4a8efd39c424e73b5206a8_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "Sách - Sherlock Holmes toàn tập - Tập 1(bìa cứng)",
        oldPrice: "₫174.000",
        price: "₫85.000",
        sell: "Đã bán 47.2k",
        sales: "",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item23",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-ligu80mzi49820_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "Tượng Phật Thích Ca Ngồi Thiền 25cm trang trí nhà phong thủy Sen Việt",
        oldPrice: "₫2.500.000",
        price: "₫2.007.500",
        sell: "Đã bán 1.4k",
        sales: "Giảm 10%",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item24",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lfyut0ygz01ja0_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "Trà Thiết Quan Âm Hảo Hạng (nguyên Túi Hút Chân Không 250 gram)",
        oldPrice: "₫445.000",
        price: "₫435.000",
        sell: "Đã bán 66",
        sales: "Giảm đ87k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item25",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lo73t1drd6nra8_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "[LOẠI 1 CỨNG CÁP] Kéo Nhật SK5 đa năng siêu bền, Kéo Thép nhập khẩu Nhật Bản cắt xương gà,vịt đa năng siêu bền",
        oldPrice: "₫18.000",
        price: "₫10.000",
        sell: "Đã bán 4.4k",
        sales: "Giảm đ10k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item26",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-ln9g6dauhfzn8a_tn",
        secondImg: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
        name: "Bảng Phấn Mắt Nhũ 9  Baby Tông Màu Nâu Cam Vàng Siêu HOT  A521",
        oldPrice: "₫27.000",
        price: "₫13.000",
        sell: "Đã bán 10.1k",
        sales: "",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item27",
        firstImg: "https://down-vn.img.susercontent.com/file/973441d3bf85c25691e789b6b77317f1_tn",
        secondImg: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
        name: "Giày nam - Sale kịch sàn Giày nam 2021 hàng mới về siêu chất lượng",
        oldPrice: "₫200.000",
        price: "₫117.000",
        sell: "Đã bán 1.4k",
        sales: "Giảm đ50k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
                display: "block"
    },
    {
        id: "item28",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lnqnokjpqi25a7_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "Áo Khoác bomber Chữ H nam nữ unisex , Áo khoác bóng chày chất nỉ bông mềm mịn HOT 2023 M02",
        oldPrice: "₫370.000",
        price: "₫159.000",
        sell: "Đã bán 7.2k",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item29",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lllyim4xun2n55_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "Dưỡng chất cho da dầu mụn Garnier Bright Complete Anti-Acnes Booster Serum 4% [Niacinamide, BHA, AHA, Vitamin C] 30ml",
        oldPrice: "₫500.000",
        price: "₫279.000",
        sell: "Đã bán 75.7k",
        sales: "Giảm 20%",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item30",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lio9o6m4uxhod2_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "Áo thun nam tay ngắn, áo phông nam cao cấp chất cotton thoáng mát in hình Kì Lân CZ628",
        oldPrice: "₫600.000",
        price: "₫49.000",
        sell: "Đã bán 47",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item31",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-ljunuiqn5zn899_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "[CHÍNH HÃNG] Nước Uống Detox Cần Tây Diếp Cá Mật Ong DAILY EFFECT (hộp 14 gói)",
        oldPrice: "₫40.000",
        price: "₫178.800",
        sell: "Đã bán 19.3k",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item32",
        firstImg: "https://down-vn.img.susercontent.com/file/sg-11134201-22090-mjd16jtyethv63_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "Túi xách YADOU vải canvas thiết kế cỡ lớn phong cách nhật bản thời trang cao cấp cho nam",
        oldPrice: "₫463.000",
        price: "₫89.000",
        sell: "Đã bán 10.8k",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item33",
        firstImg: "https://down-vn.img.susercontent.com/file/594ac126328aa851ecdf51c2e5f54231_tn",
        secondImg: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
        name: "(ST222 Shop) Tất nam cổ ngắn 100% cotton tự nhiên mềm mịn, co giãn tốt, kháng khuẩn khử mùi cực tốt",
        oldPrice: "₫33.700",
        price: "₫10.800",
        sell: "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item34",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lh75yaqrlelufe_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "Áo sơ mi nam tay ngắn phong cách đường phố màu sặc độc đáo MENFASHION1989 MSM 007",
        oldPrice: "₫430.000",
        price: "₫156.600",
        sell: "Đã bán 9.9k",
        sales: "Giảm đ5k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item35",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lihdk696perw6d_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "Dép quai ngang nam mẫu mới in VL dập nổi đẹp mắt.Dép da mang phong cách lịch lãm cho phái mạnh MÃ GDP-",
        oldPrice: "₫95.000",
        price: "₫79.980",
        sell: "Đã bán 2.4k",
        sales: "Giảm đ5k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item36",
        firstImg: "https://down-vn.img.susercontent.com/file/898d156b4ca3967b1f000c159fe09726_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "Nồi cơm điện International 1.8 lít KS-1800T nhập khẩu từ Thái Lan, chất lượng vượt trội, nấu cơm ngon trọn vị - Bevano",
        oldPrice: "₫1.000.000",
        price: "₫879.000",
        sell: "Đã bán 1",
        sales: "",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item37",
        firstImg: "https://down-vn.img.susercontent.com/file/d1cab232d992c6f22de572f8d2686a09_tn",
        secondImg: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
        name: "Sữa Chống Nắng Dưỡng Da Kiềm Dầu Bảo Vệ Hoàn Hảo Anessa Perfect UV Sunscreen Skincare Milk SPF50+ PA++++ 60ml",
        oldPrice: "₫888.000",
        price: "₫715.000",
        sell: "Đã bán 697",
        sales: "",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item38",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134211-23030-s11hzk5saeov28_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-61996021cc7ad8730f7c2d735f2894d0",
        name: "Áo Hoodie Doncle Level In Nhũ Kim Tuyến Chữ Vàng Mẫu Mới Nhất - Phong Cách Bad Boy Siêu Phẩm Chào Đông 2023",
        oldPrice: "₫232.000",
        price: "₫125.000",
        sell: "Đã bán 4.7k",
        sales: "",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item39",
        firstImg: "https://down-vn.img.susercontent.com/file/0db3fd279f76a2523240c08d05d537ba_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-61996021cc7ad8730f7c2d735f2894d0",
        name: "Áo phao cho bé trai bé gái , Áo phao tai gấu QC siêu nhẹ siêu ấm cho bé",
        oldPrice: "₫330.000",
        price: "₫125.000",
        sell: "Đã bán 12",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item40",
        firstImg: "https://down-vn.img.susercontent.com/file/2023c32af72d810545680212b4d1c061_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "Dép Kẹp nữ quai ngang siêu dễ thương, mẫu dép tông nữ hot nhất 2023 - VeoStore",
        oldPrice: "₫40.000",
        price: "₫79.900",
        sell: "Đã bán 1.9k",
        sales: "",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item41",
        firstImg: "https://down-vn.img.susercontent.com/file/13726e71cac267d410a2b0e5ac608abc_tn",
        secondImg: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
        name: "Giày Thể Thao Thoáng Khí Thoải Mái Phong Cách Mới Cho Đàn Ông Trung Niên",
        oldPrice: "₫22.000",
        price: "₫66.888",
        sell: "Đã bán 806",
        sales: "Giảm đ2k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item42",
        firstImg: "https://down-vn.img.susercontent.com/file/3d046f4b57359ab260b46ee7bc1046ac_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-cd8556906eb64475cae8a80b7849daf8",
        name: "Người tuyết treo cây thông trang trí Giáng Sinh",
        oldPrice: "₫9.800",
        price: "₫9.500",
        sell: "Đã bán 217",
        sales: "Giảm đ2k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "block"
    },
    {
        id: "item43",
        firstImg: "https://down-vn.img.susercontent.com/file/sg-11134201-22120-wxx0azg8mmlvc6_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-729f3e26d692ee487c9adba49a6dcdd6",
        name: "Balo Đi Học Đi Chơi Nam Nữ Thời Trang Hàn Quốc Nhiều Ngăn Tiện Dụng đựng vừa laptop 15.6 inch NS115",
        oldPrice: "₫5.000",
        price: "₫1.100",
        sell: "Đã bán 6.1k",
        sales: "",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "none"
    },
    {
        id: "item44",
        firstImg: "https://down-vn.img.susercontent.com/file/cn-11134207-7r98o-logi25suk80ye6_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-5a4aa67471d5517fe615f9774b9f18a1",
        name: "Đồ chơi khối xây dựng Giáng sinh Đồ Chơi Xếp Hình lego Ông Già Noel Vui Nhộn Cho Bé",
        oldPrice: "₫52.000",
        price: "₫18.000",
        sell: "",
        sales: "",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "none"
    },
    {
        id: "item45",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lncf335ji5bu4a_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-729f3e26d692ee487c9adba49a6dcdd6",
        name: "Giày sandal mũi nhọn phối quai ngọc đế 3cm xinh xắn nữ tính trẻ trung - Mã G61",
        oldPrice: "₫180.000",
        price: "₫145.000",
        sell: "Đã bán 15",
        sales: "Giảm đ5k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "none"
    },
    {
        id: "item46",
        firstImg: "https://down-vn.img.susercontent.com/file/sg-11134201-7rbmb-lo3euxyall4hd2_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "FC07 Sét Nhung QC Phối Viền, Sét Bộ Ngủ Cho Nữ Sang Chảnh Nhẹ Nhàng Theo Phong Cách Hàn Quốc - Fashion Clothes",
        oldPrice: "₫8.000",
        price: "₫3.099",
        sell: "Đã bán 1k",
        sales: "",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua kèm deal độc quyền",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "none"
    },
    {
        id: "item47",
        firstImg: "https://down-vn.img.susercontent.com/file/sg-11134201-7rbm3-lmssx4is7j95a6_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-729f3e26d692ee487c9adba49a6dcdd6",
        name: "Ôp Điện Thoại Silicon Dẻo Đính Búp Bê 3d Dễ Thương Cho iphone 11 13 12 14 pro max x xr xs max 6 7 8 plus Ốp",
        oldPrice: "₫89.000",
        price: "₫1.000",
        sell: "Đã bán 2.5k",
        sales: "",
        flash: "flash-sales",
        nameShop: "TUNG Home Decor",
        voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Combo khuyến mãi",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "none"
 
    },
    {
        id: "item48",
        firstImg: "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lk5bbvlhmpz6d6_tn",
        secondImg: "https://down-vn.img.susercontent.com/file/vn-50009109-ebc08b7aa63078ee09c4c2d85f810320",
        name: "Váy suông dài, đầm suông bầu chất cotton cao cấp Magaret (sẵn - ảnh thật)",
        oldPrice: "₫300.000",
        price: "₫297.500",
        sell: "Đã bán 29",
        sales: "Giảm đ15k",
        flash: "",
         nameShop: "TUNG Home Decor",
         voucher: "Voucher giảm đến ₫5k",
        imgvoucher: "Mới",
        ship: "Giảm ₫15.000 phí vận chuyển đơn tối thiểu ₫50.000; Giảm ₫25.000 phí vận chuyển đơn tối thiểu ₫99.000",
        display: "inline-block",
        combo: "Deal Sốc",
        discount: "Mua 3 giảm ₫4.000",
        backgroundColor: "transparent",
        inputOrText: `<input type="checkbox" style="width: 15px;"></input>`,
        imgOrText: `<img src="https://down-vn.img.susercontent.com/file/vn-50009109-8bbfef7c0d2b19a18f92ddcc25a9cdaa" alt=""></img>`,
         size: "TRẮNG,M 40-50KG",
         display: "none"
    }
];